### ISSUE TITLE
ImportError: cannot import name 'EnglishPhonemes' from 'voxpopuli'

### ISSUE THREAD

**Issue by bakszero** [hadware/voxpopuli#14]
# Comments

I see that the latest version of `phonemes.py` file does not contain a class for `EnglishPhonemes`, but rather only a class for `BritishEnglishPhonemes` which seems to be the cause for an error when importing `EnglishPhonemes` as follows:

`from voxpopuli import EnglishPhonemes`
`ImportError: cannot import name 'EnglishPhonemes' from 'voxpopuli' (/home/$USER/anaconda3/lib/python3.7/site-packages/voxpopuli/__init__.py)`

# Possible Solution
Either the class must be renamed or the README must be updated to reflect this. I can send in a pull request for the latter but since you mention the following: 

> For French, Spanish, American English, British English and german, the phoneme codes used by espeak and mbrola are available as class attributes like in the Englishphonemes class used before.

I'm assuming you have some design decision w.r.t `EnglishPhonemes` class, would love to know! Great piece of work btw! :D

**Comment by hadware** [comment]
Thanks for your PR, sorry for this. I'll try setting up an actual Readthedocs documentation btw (at least to autodoc the API).

**Comment by bakszero** [comment]
That'd be great, thanks!
