### ISSUE TITLE
The Voxpopuli Documentation is empty!

### ISSUE THREAD

**Issue by j-j-kam** [hadware/voxpopuli#18]
Hi, I would like to access the documentation that was on the website, but the sections are completely empty! Why? Please, add it.

**Comment by hadware** [comment]
Ah! Sorry, i left it as a todo and kind of forgot about it (and kind of thought that no one cared aha). I'll take care of it ASAP.

**Comment by hadware** [comment]
I wrote some documentation. tell me if you think that something is missing or not clear enough.
